// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpCnKVFcFecof3SJEMgYiUid4xFlMuah8',
    appId: '1:240732290824:web:ec865244459af595b936bd',
    messagingSenderId: '240732290824',
    projectId: 'chatappflutter-42ed0',
    authDomain: 'chatappflutter-42ed0.firebaseapp.com',
    storageBucket: 'chatappflutter-42ed0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXI-zpqXDzQUOgbYJknFG1-q0Dc4T1J1U',
    appId: '1:240732290824:android:4ec17b8ab6286f6eb936bd',
    messagingSenderId: '240732290824',
    projectId: 'chatappflutter-42ed0',
    storageBucket: 'chatappflutter-42ed0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByMQ_v_Mzvj1fLOaspAJqmmfXkUdVa9JY',
    appId: '1:240732290824:ios:6faa913525acfef6b936bd',
    messagingSenderId: '240732290824',
    projectId: 'chatappflutter-42ed0',
    storageBucket: 'chatappflutter-42ed0.appspot.com',
    androidClientId: '240732290824-lgvpqbamn0jr1c8vrps14qama3uhtacb.apps.googleusercontent.com',
    iosClientId: '240732290824-uh3hdpqe4l8dqqk09kgrf8o3nr0s2722.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByMQ_v_Mzvj1fLOaspAJqmmfXkUdVa9JY',
    appId: '1:240732290824:ios:6faa913525acfef6b936bd',
    messagingSenderId: '240732290824',
    projectId: 'chatappflutter-42ed0',
    storageBucket: 'chatappflutter-42ed0.appspot.com',
    androidClientId: '240732290824-lgvpqbamn0jr1c8vrps14qama3uhtacb.apps.googleusercontent.com',
    iosClientId: '240732290824-uh3hdpqe4l8dqqk09kgrf8o3nr0s2722.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled',
  );
}
